# Dependencies
markdown:         kramdown # for MathJax to work
pygments:         true

# Permalinks
permalink:        "/:title"

# Setup
title:            The Shiny Dinosaur
tagline:          'some personal musings'
description:      ''
url:              http://shinydinosaur.github.io

author:
  name:           'Shiry Ginosar'
  url:            http://shinydinosaur.github.io

paginate:         1

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/shinydinosaur/shinydinosaur.github.io
